### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by MahmoudMabrok** [MoatazBadawy/Sunset-hadith#2]
https://github.com/MoatazBadawy/Sunset-hadith/blob/b2bd9d6fb5df2502b9ba37ca64d30f16e796d8b0/app/src/main/java/com/moataz/afternoonhadeeth/ui/MainActivity.kt#L53

Make a `Util` class for **intents**, it should accept **link** and open It

**Comment by MoatazBadawy** [comment]
Check out the project repo update.
