### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by MahmoudMabrok** [MoatazBadawy/Sunset-hadith#3]
https://github.com/MoatazBadawy/Sunset-hadith/blob/4fc93130ec7336cf42aa281f6a0e95ad887d7d68/app/src/main/java/com/moataz/afternoonhadeeth/utils/Intents.kt#L7

make it **object** ,  and no need to extend Intent 

so 

``` kotlin 
object IntentHelpers {

  fun open(){
  }

}
```

**Comment by MoatazBadawy** [comment]
Great. Check out the project 👍🏻

**Comment by MahmoudMabrok** [comment]
why it labeled as `invalid`

**Comment by MoatazBadawy** [comment]
I think it happened by mistake. I have updated the label 😁
