### ISSUE TITLE
Place a link to play store to convert repository visits to app downloads.

### ISSUE THREAD

**Issue by Breens-Mbaka** [MoatazBadawy/Sunset-hadith#4]

**Comment by MoatazBadawy** [comment]
done

**Comment by Breens-Mbaka** [comment]
😂thanks for closing this

**Comment by MoatazBadawy** [comment]
Hahaha, I saw this a while ago but I preferred to put the link after publishing the final version of the application 😁, and thank you very much for this suggestion :)
