### ISSUE TITLE
Wait for the update

### ISSUE THREAD

**Issue by patrickwilson111** [MoatazBadawy/Sunset-hadith#6]
slam bro Ramadan Kareem
My brother, the application is not complete, there are errors, images appear frequently
There is a crash when working on the application
Is this the latest version or is it old?
Wait for the update

**Comment by MoatazBadawy** [comment]
Waalaikumsalam brother,
Yes, this is the latest open-source version on githup. No problem, I will check out the problem you had with the images.

**Comment by MahmoudMabrok** [comment]
@patrickwilson111 
please share the log if this possible. 
also share the device/emulator specficiation you are using. 
will be helpful if you submit a video/gif for  the issue. 

and we are sorry if you faced any issues.

**Comment by patrickwilson111** [comment]
![1](https://user-images.githubusercontent.com/103704444/163725855-c45379a5-8919-404b-a315-8e1ba97264e5.png)

**Comment by patrickwilson111** [comment]
Thank you for your attention. I tried to look for the crack, where did it happen to me? I couldn't find the glitch. Where is it? I apologize
There is a picture attached to duplicate the pictures
Second, is it the same version on Google Play?
https://play.google.com/store/apps/details?id=com.moataz.afternoonhadeeth

Or is it an attempt to design an application that works with the same features?

![unnamed](https://user-images.githubusercontent.com/103704444/163725924-9a6fd089-a756-4810-8f6a-9c4d2b2e219d.png)

**Comment by MoatazBadawy** [comment]
Hello again, 
Yeah, as shown in the image above we used the same images for just testing the application "Take a look at the API JSON images file, you will find the same URL we have used", so you can replace URLs with all images you want.

As your second comment, the latest version is private, so it is not public for all (we are sorry for this). If you want to create an image screen as we have you can simply use Viewpager2 with tablayout and fragments, check out this youtube tutorial from here: https://www.youtube.com/watch?v=8dYuBP8bvpU
and if you want to create tablayout like we have you may find this link useful: https://medium.com/nerd-for-tech/how-to-create-custom-tab-layout-in-android-android-studio-java-83e87eb837ad

hope you found what you want bro.
and Ramadan Mubarak for you and your family.
